"""add at_closed to tasks

Revision ID: f8afca6f6d7d
Revises: 928fcc3f31c3
Create Date: 2025-12-07 19:09:53.690586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8afca6f6d7d'
down_revision: Union[str, Sequence[str], None] = '928fcc3f31c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('at_closed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'at_closed')
    # ### end Alembic commands ###
